### ISSUE TITLE
Network Architecture

### ISSUE THREAD

**Issue by mbellitti** [mbellitti/wikiart-classifier#10]
I'll start experimenting using the `keras_classify` notebook, I would like to use that as the main place where the training happens.

It's easy to then convert it into a minimal script and have it run on the cluster. I'll make a new branch.

**Comment by mohitpandey92** [comment]
Since I have closed issue on transfer learning, let's use this place to discuss changes to network architecture.

**Comment by mbellitti** [comment]
We are using VGG16 followed by a few fully connected layers.

**Comment by mbellitti** [comment]
The VGG16 layers were not trained, the minimization used Adam with default hyperparameters.
