### ISSUE TITLE
Multiple tags

### ISSUE THREAD

**Issue by mbellitti** [mbellitti/wikiart-classifier#11]
Some artworks belong to multiple genres, for example a paiting about a naval painting will be of genre "marina, battle painting" while some other paintings will be just "marina" or "battle painting". How do we deal with that?

There are a few viable solutions:
1. We ignore those cases, and just drop them from the database
2. We keep only one of the two tags (at random?)
3. We duplicate the database entry, and label each one with a single tag

Option 3 is the most appealing to me and it should take a few minutes to do it in pandas, but the other two options should not be disregarded immediately: these kind of images are intrinsically ambiguous, will il make the NN more confused?

**Comment by mbellitti** [comment]
Now that I'm looking a bit more at those examples, some of them are hierarchical specifications: for example 'landscape,cityscape' and 'landscape,cloudscape'. What should we do?

**Comment by albrechtjan** [comment]
I actually like the idea of using the picture twice with different tags.

**Comment by albrechtjan** [comment]
And if we want to be fancy, we could use the softmax output as the input of a second NN that determines whether the picture is single or double labeled. 
(marina, 0.12, landscape 0.07, portrait 0.02, ...) ---> NN ---> single/double

**Comment by mohitpandey92** [comment]
If multiple tags are not hierarchical, then we can use the picture twice with different tags. If they are hierarchical, then probably the only way we can see structure globally is by running some clustering algorithms.

**Comment by mbellitti** [comment]
For training we dropped all the tags below the highest level. Anything else would have been a serious problem in itself.
