### ISSUE TITLE
Running on the Cluster

### ISSUE THREAD

**Issue by mbellitti** [mbellitti/wikiart-classifier#13]
We have to figure out how to train using the cluster. It allegedly has a few nodes full of GPUs, let's set them on fire.

**Comment by mohitpandey92** [comment]
So far, while training the model, epochs are running one after another. It would be nice to run them at the same time.

**Comment by mohitpandey92** [comment]
Apparently, fit_generator already has in-built feature to run over GPU. See [here](https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py) and [here](https://keras.io/models/sequential/) under "fit_generator".

So, @mbellitti , can you try it on cluster whenever you find time?

**Comment by mbellitti** [comment]
I'm at the airport, if I can figure out how to connect to the cluster from here I'll do it

**Comment by mbellitti** [comment]
It turns out that the amazing people at the RCS have written a small guide to using Keras on the BU cluster, it's [here](http://rcs.bu.edu/examples/ML/tensorflow/). 

As of now our script can correctly import TensorFlow and recognize it's using a GPU, but for some reason it hangs when building the `ImageDataGenerator`s.

**Comment by mbellitti** [comment]
It works. We used GPUs, which made the training a blaze.
