### ISSUE TITLE
Unsupervised: clustering

### ISSUE THREAD

**Issue by mbellitti** [mbellitti/wikiart-classifier#14]
It would be cool to run t-SNE or PCA on the dataset to get an idea of the structure, I'm sure there is some insight to be gained: very likely the artworks will be clustered by aspect ratio (portrait vs. landscape) and by color (warm/cold). 
At a higher level of detail they might even be clustered by author/style/school. There are a lot of tasks we could define, for example if we just consider a subset of the data we can ask questions like:

- Given a school (impressionism) are the artworks of painters clustered? If we use a resolution high enough (256x256?) I'm sure that there is a visible effect.
- Fixed an artist, what information do the clusters convey? For example, Picasso's blue period paintings and the pencil sketches will likely be well separated.

Does anyone want to become a clustering expert?

**Comment by albrechtjan** [comment]
I'd like to but I won't have time to look into it deeply until Thursday...

**Comment by albrechtjan** [comment]
The critical point of this is getting a proper feature vector from our images. 
Here https://github.com/ml4a/ml4a-guides/blob/master/notebooks/image-search.ipynb
they use the output of the second to last layer of VGG-16 as a feature vector. Sounds like a brilliant idea.

**Comment by mohitpandey92** [comment]
That sounds great! On the branch "transfer_learning", I have used VGG-16 as pre-trained CNN layers before adding dense layers to it. Feel free to open a new branch and make changes to the code, whenever you find time.

**Comment by albrechtjan** [comment]
Data visualisation with PCA/t-SNE works good in principle unsing the pretrained VGG16. However, no clear separation of clusters, yet. E.g. different artists can't be distinguished (test with michelangelo and lyonel feininger). We will have to check if the results get better, if we use the the dense layers that we trained ourselves.

**Comment by albrechtjan** [comment]
Visualisation with our trained network performs far worse than using the original VGG as a feature extractor. My guess is that our network is less sensitive to subtle differences because our number of possible classes is far smaller than in the imagenet challenge (there they have 1000).
