### ISSUE TITLE
Scraping images and metadata

### ISSUE THREAD

**Issue by mbellitti** [mbellitti/wikiart-classifier#2]
The work already in the repo is great, this issue is just a place to discuss how to proceed from there.

It looks like WikiArt has a few pages that are text lists, for example this is the page for all artists that start with an "A": 

https://www.wikiart.org/en/Alphabet/a/text-list

The artworks for a given artist are listed in pages that look like this: 

https://www.wikiart.org/en/hans-von-aachen/all-works/text-list

**Comment by albrechtjan** [comment]
In combination those two url patterns should give us all artworks with the right loops.
Do you think it is better to get a list of all urls first, and then get the information and pictures looping over that list or do it in one go?
With this structure in the urls I think we don't even need scrapy anymore. Simple python string manipulation should do.

**Comment by mbellitti** [comment]
Let's try a simple approach with string manipulation on a branch and let's use bs4/scrapy on another. 
Probably those libraries offer some convenient functions to deal with exceptions and metadata extraction.

I haven't played with bs4 yet, so I haven't a strong opinion either way.

**Comment by mohitpandey92** [comment]
So, let's divide the task between us: one of us can try doing simple string manipulation and the the other person can try bs4/scappy. Let's do it on different branches as Matteo said, and see which one is better for us. @janpfsr, are you doing string manipulation? I can start looking into scrapy.

**Comment by albrechtjan** [comment]
I will upload a string manipulation version to get all necessary urls as soon as my test has finished (hopefully positively). That takes some time.
I use bs4 to navigate to the urls on the pages, though.

**Comment by mbellitti** [comment]
Hold on a second on that, I'm looking at the scraper that Mohit wrote and trying to simplify it. I should be done by tonight, then you can call those functions inside your loops.

**Comment by albrechtjan** [comment]
What I am doing doesn't depend on those functions, yet. At the moment I independently extract a list of the urls of all artworks. This list then can be fed into whatever functions we want.

**Comment by mbellitti** [comment]
That's perfect.

**Comment by mbellitti** [comment]
Following the approach of the answer [here](https://stackoverflow.com/questions/24398044/downloading-a-lot-of-files-using-python) I've parallelized the loop to download the metadata.

Downloading the first 1000 artworks (no images) took 5min40s on my laptop, so downloading the whole thing should take roughly 15h. We can probably push it a bit more (spawning more processes), but the order of magnitude is right.

**Comment by albrechtjan** [comment]
I have added information about the available file sizes to our metadata. However, the drawback is that it doubles (or maybe even triples) the filesize because urls are long and there are always five or so files.

**Comment by albrechtjan** [comment]
We successfully downloaded all metadata.
