### ISSUE TITLE
Possible Problems for Extracting Metadata

### ISSUE THREAD

**Issue by albrechtjan** [mbellitti/wikiart-classifier#4]
I just realized that there is the category "original" title. 
e.g. https://www.wikiart.org/en/david-burliuk/futuristic-woman-1911
In this example the kyrillic letters can not be parsed. They yield instances of '?' but no error is returned.

**Comment by albrechtjan** [comment]
We could exclude this category from being written into the dictionary.

**Comment by mbellitti** [comment]
We can do one of two things:
1. Ignore the category
2. Save all the strings as unicode (which we should probably be doing anyway)

I'm leaning on the second option, but I don't know if it's easy.

**Comment by mohitpandey92** [comment]
Good catch, @janpfsr ! I would vote for ignoring the category because I don't see any prediction task that we can do with original title.

**Comment by mbellitti** [comment]
I can confirm that bs4 natively supports unicode, so if we use that to  get the metadata that's not an issue. I'll try to parse the page you linked and see what it looks like.

**Comment by mbellitti** [comment]
All the metadata is downloaded.
