### ISSUE TITLE
merging the two metadata dictionaries

### ISSUE THREAD

**Issue by albrechtjan** [mbellitti/wikiart-classifier#5]
The data in the json tag is not identical to the data displayed to the right of the picture on an wikiart artwork page. 
For example style and genre are not in the json while information like max resolution and id do not appear to the right of the picture.
Furthermore we have to decide which pictures to download. The image link in the json appears to direct to the picture of largest resolution. The picture displayed have roughly similar resolution.

**Comment by mbellitti** [comment]
Good point. It looks like you can specify what size of the picture you want by appending some qualifier (like "!Large") right after the base name, which is what is returned by json.

I say we should merge the two, keeping everything. We can then write a function to actually fetch the images and specify what size we want as an argument of that function.

I'll do it.

**Comment by mbellitti** [comment]
It looks like the only two extra properties that are not present in the JSON version are "Style" and "Genre", so I'll include those two.

**Comment by albrechtjan** [comment]
I think 'Media' is also missing.

**Comment by mbellitti** [comment]
There is a class called "dictionary-values " (sic. including the trailing space) in the source, that seems to have all and only the data we need. I'll see if I can use that.

**Comment by mbellitti** [comment]
I've merged the two functions, the metadata now uses both sources: the JSON file and the html tags on the page.
