### ISSUE TITLE
ArtWork class

### ISSUE THREAD

**Issue by mbellitti** [mbellitti/wikiart-classifier#6]
I think it would be nice to wrap the scraping functions inside a class, so that we can do something like

Create an object with all the metadata as attributes:
`>>> feastofgods = ArtWork(https://www.wikiart.org/en/giovanni-bellini/the-feast-of-the-gods-1514)`
this is memory efficient, it's just text.

Then we load in memory the image when we have to train on it:
`>>>feastofgods.fetch_image()`
if we decide to save the images on disk, this method could check if the image is already there and otherwise download it.

**Comment by albrechtjan** [comment]
We should add the functionality to choose which file_size we want to download. 
Right now we are taking the image url from the json file which maps to the largest file. 
For this reason it may be not a bad idea to also include the list with the different sizes available into our metadat.

**Comment by mbellitti** [comment]
Sounds good, I'll do that. How do you know what sizes are available?

**Comment by albrechtjan** [comment]
I think we should again talk about what we want the download_image method to do.
First, I would really add the option to specify the directory in which the image is saved.
Second, right now we are writing all downloaded images to the disk. In case we want to keep our local disks clean, we would have to include the delete routine into the routine collecting the batches. I think it would be easier and more intuitive to include it directly into the download function.
My suggestion would be, that the method has a switch 'save_local' and a switch that toggles whether not only the filename but also the file itself is returned.

**Comment by mbellitti** [comment]
We ended up not creating this class, all the images have been downloaded (in two different resolutions) so w don't need the download_image method. Closing.
