### ISSUE TITLE
Image Preprocessing

### ISSUE THREAD

**Issue by mbellitti** [mbellitti/wikiart-classifier#7]
Keras has a set of functions in the `keras.preprocessing.image` submodule that help with data augmentation and image handling, the documentation is [here](https://keras.io/preprocessing/image/).

[This](https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html) and [this](https://medium.com/@vijayabhaskar96/tutorial-on-keras-flow-from-dataframe-1fd4493d237c) are tutorials I have found that use those functions in conjunction with pandas dataframes.

We should learn how to use those.

**Comment by albrechtjan** [comment]
To use the flow_from_dataframe functionality in the second tutorial, we have to manipulate the underlying class DataFrameIterator which is the class of the object returned by the flow_from_dataframe method of the ImageDataGenerator class.
I opened a new branch with the relevant parts of the code which would have to be manipulated. 
Besides some routines for assertion of the right file structure that, which we can't use if we load the images on the fly, only the line where the images are loaded would have to be replaced.

**Comment by mbellitti** [comment]
I'm not sure I understand everything you said, but it looks like it's good
news

**Comment by albrechtjan** [comment]
To unpack it a little... 
- model.fit_generator(generator=train_generator,...)
 - train_generator=datagen.flow_from_dataframe(
dataframe=traindf, ...)
 - train_generator is an instance of the DataFrameIterator class.
- Thus, we have to change the part in the DataFramIterator class that loads the pictures. 

If we can do that we can use all the other functionalities without problems.

**Comment by mbellitti** [comment]
The `flow_from_dataframe` method works, I've tried training and it looks like it's doing something. I haven't evaluated the model yet, but the fact that it doesn't throw any exception is encouraging. 

As soon as I figure out what exactly the preprocessing pipeline can do we can discuss what transformation we want to allow.

**Comment by mbellitti** [comment]
We used the Keras default: 20 deg rotation, no flipping, rescaling to 256x256.
