### ISSUE TITLE
JSON Decoder Error for a specific url

### ISSUE THREAD

**Issue by mohitpandey92** [mbellitti/wikiart-classifier#8]
When I use function meta_data of the file src/image_scraper.py for [this](https://www.wikiart.org/en/douglas-abdell/diamond-mirror-x-k) page, it gives  the following error:

```
Traceback (most recent call last):
  File "../src/image_scraper.py", line 49, in get_meta_data
    meta_data = json.loads(painting_json_string.lower().split("=")[1])
  File "/home/mohit/anaconda2/envs/py36/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/mohit/anaconda2/envs/py36/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/mohit/anaconda2/envs/py36/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 82 (char 81)

```
I haven't investigated this in detail so far.

**Comment by mohitpandey92** [comment]
I was wondering : is it an isolated url or there are more examples of such urls which give error?

**Comment by mbellitti** [comment]
I don't know, but I admit I have not tested extensively those functions. Could you try using a few more urls from the list that Jan compiled?

**Comment by mbellitti** [comment]
It looks like it's a problem of that page, I haven't figured out exactly what.
I suspected the problem was that it's a sculpture (so maybe the page was slightly different) but the function works with other sculptures.

**Comment by mbellitti** [comment]
Found the problem: the title contains a "=". 

This symbol creates some confusion when building the `meta_data` dictionary. I'll try to find a solution.

**Comment by mbellitti** [comment]
Solved. Having special symbols in the artwork title (or other fields) shouldn't be a problem, now.
